### ISSUE TITLE
Menu navbar ordering

### ISSUE THREAD

**Issue by jasdumas** [noreastrconf/noreastrconf.github.io#1]
It appears that the addition of a `weight` param to the menu.main will direct the correct order of pages

Source: https://github.com/calintat/minimal/blob/master/exampleSite/config.toml#L23

Example: 

```yml
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
```

**Comment by jasdumas** [comment]
this gave a build error but it successfully re-positioned menu items 🤷‍♀️

**Comment by jhollist** [comment]
@jasdumas was it a GitHub build error?  That makes sense if so (if I am remembering things correctly).  This is served via netlify.  Everything I learned, I learned from https://bookdown.org/yihui/blogdown/deployment.html#deployment ! I **think** this should all work on push...
