### ISSUE TITLE
Need to re-direct https://noreastrconf.github.io to https://noreastrconf.com

### ISSUE THREAD

**Issue by jhollist** [noreastrconf/noreastrconf.github.io#3]

**Comment by jasdumas** [comment]
I wonder if that could be solved by adding thins in the Settings section:
![screen shot 2018-04-27 at 2 06 17 pm](https://user-images.githubusercontent.com/6685750/39377779-570e1e10-4a24-11e8-9ad5-2cc8c2fc5a79.jpeg)

I need to read through the `blogdown` tutorial so I don't break things 😄

**Comment by jasdumas** [comment]
I think this solves this: https://github.com/noreastrconf/noreastrconf.github.io/commit/9123b13344d36296b8da7e1e52138ac9422265c0
