### ISSUE TITLE
Finalize speaker list

### ISSUE THREAD

**Issue by richierocks** [noreastrconf/noreastrconf.github.io#4]
Wildly guessing as to the speakers' choices of topics, but it's likely to be

### Bioconductor

- Lori Shepherd
- Mary Piper

### Developer stuff

- Bob Rudis
- Simon Urbanek
- Noam Ross

### Epidemiology/medical applications

- Monika Wahi
- Mike Kane

### Business applications 

- Emily and possibly Dave Robinson
- Tanya Cashorali

### Data science skills

- Mara Averick
- JD Long

From the last meeting, there was a concern that

>  Pressing items are diversity of speakers:  we've done a good job with gender diversity, but the line up is all white at this point.

This isn't quite true (Monika is Indian American), and we are short on free slots for speaker, but yes, let's try to add 1 more non-white speaker. We don't currently have anyone speaking about Shiny *cough* @jasdumas *cough*.

**Comment by jasdumas** [comment]
lol @richierocks you can sign me up to chat about shiny if we need 😄

**Comment by richierocks** [comment]
List has been finalized!
