### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jasdumas** [noreastrconf/noreastrconf.github.io#6]
I think this should be up sooner rather than later to inform speakers and attendees of decorum for the event. It might be wise to adopt another tech conferences' CoC to leverage their hard work, such as the one from http://confcodeofconduct.com/

🖐 Seeking y'alls review for this on the CoC page of the website

> # Conference Code of Conduct
> All attendees, speakers, sponsors and volunteers at our conference are required to agree with the following code of conduct. Organisers will enforce this code throughout the event. We expect cooperation from all participants to help ensure a safe environment for everybody.

> ## Need Help?
> You have our contact details in the emails we've sent.

> ## The Quick Version
> Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers.

> ## The Less Quick Version
> Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

> Participants asked to stop any harassing behavior are expected to comply immediately.
Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualised images, activities, or other material. Booth staff (including volunteers) should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualised environment.

> If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.
If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately. Conference staff can be identified as they'll be wearing branded clothing and/or badges.

> Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.
We expect participants to follow these rules at conference and workshop venues and conference-related social events.

> Original source and credit: http://2012.jsconf.us/#/about & The Ada Initiative
> Please help by translating or improving: http://github.com/leftlogic/confcodeofconduct.com
> This work is licensed under a Creative Commons Attribution 3.0 Unported License

**Comment by jasdumas** [comment]
also @gdancik for review of the CoC and needs to get added to the GH team org 👍

**Comment by mfoos** [comment]
Great idea & work. Tomorrow I might try to pull out and bullet some “at-a-glance takehomes, if that is of interest. I don’t have my computer with me at the moment.

**Comment by jhollist** [comment]
First, just invited @gdancik to the org.  Thanks for the heads up on that.

Second, I think the CoC looks good.  Only thing I might change is to have some points of contact under the **Need Help?** section explicitly identified.  Pointing to an email for contact info doesn't feel very satisfying to me.  

I think listing two or three contacts directly on the CoC would be sufficient.  Something along the lines:

> If you have questions about the Code of Conduct or feel someone at the conference is not adhering to the Code, please let us know.  You may contact any member of the [organizing committee](), but in particular Person 1, Person 2, or Person 3 would be excellent first contacts.

Could probably be wordsmithed, but the general idea is there...

**Comment by jhollist** [comment]
Also, this happened today: https://www.r-consortium.org/announcement/2018/06/07/on-conduct-and-diversity-in-the-r-community.  

Should we reach out just to make sure we are doing stuff that advances this for the community as a whole and aren't just ad hoc'ing our own solution?

**Comment by gdancik** [comment]
@jasdumas  thanks for the shoutout and thanks @jhollist  for the invite.

Regarding contact info, the e-mail icon on the Github page points to
info@noreastrconf.com. Is this address still active. When I found the page
initially I emailed the address but my e-mail bounced back.

I agree that we should reach out to R Consortium regarding the CoC. It
looks like they will have a CoC in place by the end of the summer, and I
think it would be good if we can use or incorporate theirs with ours.

**Comment by jasdumas** [comment]
> Should we reach out just to make sure we are doing stuff that advances this for the community as a whole and aren't just ad hoc'ing our own solution?

@jhollist totally - I would assume that would also be a pre-req for applying for the small conference grant from the R Consortium however let's reach out earlier to make sure we are on a good track forward! I can start that conversation by pinging some of the folks on the [R Forwards](http://forwards.github.io/) group today!

> I agree that we should reach out to R Consortium regarding the CoC.  It
looks like they will have a CoC in place by the end of the summer, and I
think it would be good if we can use or incorporate theirs with ours.

@gdancik I agree! I wonder if it would still be good to put up a short version of the draft CoC (i.e. "Don't be a Jerk") while we apply for the small grant and work with the _R Community Diversity and Inclusion Working Group (RCDI-WG)_  and make it aware to all participants that plan to come to our Conference that this is an active priority for us as organizers (I know some participants will need to do conference budget planning earlier rather than later for funds from work/school)

**Comment by richierocks** [comment]
Existing CoCs to borrow from:.

- useR: https://user2018.r-project.org/code_of_conduct
- rstudio::conf: https://www.rstudio.com/conference/#conduct
- EARL: https://earlconf.com/2016/london/conduct
- Cascadia R: https://cascadiarconf.com/coc
- ODSC: https://odsc.com/code-of-conduct

**Comment by hturner** [comment]
It's not clear yet whether the RC working group will come up with a standard CoC by the end of the summer, or at all - the policy may simply be that sponsored conferences should have a CoC, perhaps with some guidelines for writing one or pointers to good examples. So in the meantime I would adopt one from a previous conference (perhaps with minor tweaks) - you can always update/swap the CoC  later as it only really applies during the conference itself (people sign up to it when registering). However putting it up now shows the importance you place on ensuring the conference is a welcoming and safe space.

The useR! one was revised a bit this year and includes a response team - this is like the specific points of contact @jhollist suggested.

If you go for one with a short and long version, you might take note of the advice here: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy, i.e. the long version is the official version on the website and the short version is for easy sharing, e.g. on the registration form or in an announcement at the start of the conference, still pointing to the full version.

**Comment by jhollist** [comment]
We have a draft up.  Also I joined the Consortium working group.  First meeting is coming up.  I'll dig up date and post later

**Comment by jhollist** [comment]
Not sure if these links are public or not, but if they are, details about he R Consortium Diversity and Inclusion workgroup call are at https://lists.r-consortium.org/g/rconsortium-wg-rcdi/message/6.

Also, if interested, you can join the mailing list from https://lists.r-consortium.org/g/rconsortium-wg-rcdi
